# base services
x-ut99-base: &ut99-base
  image: roemer/ut99-server:latest
  environment:
    - UT_WEBADMINUSER="admin"
    - UT_INITIALBOTS_DM=4
    - UT_MINPLAYERS_DM=4
    - UT_WEBADMINPWD="admin"
    - UT_MINPLAYERS_CTF=8
    - UT_MOTD1="Have Fun!"
    - UT_MAXPLAYERS=32
    - UT_ADMINEMAIL="admin@noxlan.co.uk"
    - UT_INITIALBOTS_CTF=8
    - UT_ADMINNAME="UTAdmin"
    - UT_ADMINPWD="admin"

x-ut2004-base: &ut2004-base
  image: ut2004:latest
  environment:
    - MAXPLAYERS="64"
    - MUTATORS=""              # Optional mutators (used only if INSTAGIB not set)
    - OTHER_OPTS=""            # Additional ?option=value options
    - LAN="1"                  # Set to 1 to disable online uplink
    - SV_PASSWORD=""           # Optional server join password
    - RCON_PASSWORD="noxlan"   # Admin password

services:

  l4d2-campaign:
    image: l4d2-metamod:latest
    container_name: gameserver-l4d2-campaign
    env_file:
      - rcon.env
    environment:
      - MAP="c2m1_highway"
      - MP_GAMEMODE="coop"
      - MAX_PLAYERS=4
      - HOSTNAME="NoxLAN - Left 4 Dead 2 - Campaign"
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.10"
    stdin_open: true
    tty: true
    restart: unless-stopped

  l4d2-versus:
    image: l4d2-metamod:latest
    container_name: gameserver-l4d2-versus
    env_file:
      - rcon.env
    environment:
      - MAP="c2m1_highway"
      - MP_GAMEMODE="versus"
      - MAX_PLAYERS=8
      - HOSTNAME="NoxLAN - Left 4 Dead 2 - Versus"
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.11"
    stdin_open: true
    tty: true
    restart: unless-stopped

  l4d2-versus-ms:
    image: l4d2-multislot:latest
    container_name: gameserver-l4d2-versus-ms
    env_file:
      - rcon.env
    environment:
      - MAP="c2m1_highway"
      - MP_GAMEMODE="versus"
      - MAX_PLAYERS=16
      - HOSTNAME="NoxLAN - Left 4 Dead 2 - Versus (8v8)"
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.12"
    stdin_open: true
    tty: true
    restart: unless-stopped

  l4d2-campaign-ms:
    image: l4d2-multislot:latest
    container_name: gameserver-l4d2-campaign-ms
    env_file:
      - rcon.env
    environment:
      - MAP="c4m1_milltown_a"
      - MP_GAMEMODE="coop"
      - MAX_PLAYERS=8
      - HOSTNAME="NoxLAN - Left 4 Dead 2 - Campaign (8 players)"
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.13"
    stdin_open: true
    tty: true
    restart: unless-stopped

  l4d2-survival-ms:
    image: l4d2-multislot:latest
    container_name: gameserver-l4d2-survival-ms
    env_file:
      - rcon.env
    environment:
      - MAP="c6m1_riverbank"
      - MP_GAMEMODE="survival"
      - MAX_PLAYERS=8
      - HOSTNAME="NoxLAN - Left 4 Dead 2 - Survival (8 players)"
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.14"
    stdin_open: true
    tty: true
    restart: unless-stopped

#todo add bot support with
#https://web.archive.org/web/20240321092155/http://filebase.bots-united.com/uploads/podbot_full_V3B22.zip
  cs-1-6:
    image: cs16ds/server:latest
    container_name: gameserver-cs-1-6
    ports:
      - 26900:26900/udp
      - 27020:27020/udp
      - 27015:27015/udp
      - 27015:27015
    environment:
      - MAXPLAYERS=32
      - START_MAP="de_dust"
      - SERVER_NAME="NoxLAN - Counterstrike"
      - FRIENDLY_FIRE=1
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.20"
    restart: unless-stopped

  gameserver-blackmesa:
    image: blackmesa:latest
    container_name: gameserver-blackmesa
    environment:
      - MAXPLAYERS=24
      - START_MAP="bm_c0a0a"
      - SERVER_NAME="NoxLAN - Black Mesa"
      - FRIENDLY_FIRE=1
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.22"
    stdin_open: true
    tty: true
    restart: unless-stopped

  css:
    image: css-metamod:latest
    container_name: gameserver-css
    env_file:
      - rcon.env
    environment:
      - BOT_QUOTA=12
      - MP_AUTOTEAMBALANCE=1
      - MP_FRIENDLYFIRE=1
      - MP_MAXROUNDS=7
      - MP_TIMELIMIT=10
      - MAP="de_dust"
      - MAX_PLAYERS=24
      - SV_HOSTNAME="NoxLAN - Counterstrike Source"
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.30"
    stdin_open: true
    tty: true
    restart: unless-stopped

  css-hideandseek:
    image: css-hideandseek:latest
    container_name: gameserver-css-hideandseek
    env_file:
      - rcon.env
    environment:
      - MAP="cs_office"
      - MAX_PLAYERS=24
      - MP_TIMELIMIT=10
      - SV_HOSTNAME="NoxLAN - Counterstrike Source - (Hide and Seek)"
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.31"
    stdin_open: true
    tty: true
    restart: unless-stopped

  css-gungame:
    image: css-gungame:latest
    container_name: gameserver-css-gungame
    env_file:
      - rcon.env
    environment:
      - BOT_QUOTA=12
      - MAP="de_chateau"
      - MAX_PLAYERS=24
      - MP_TIMELIMIT=15
      - MP_ROUNDTIME=0
      - SV_HOSTNAME="NoxLAN - Counterstrike Source - (GunGame)"
      - LAN=1
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.32"
    stdin_open: true
    tty: true
    restart: unless-stopped

  # csgo:
  #   image: cm2network/csgo:sourcemod
  #   container_name: gameserver-csgo
  #   environment:
  #     - SRCDS_RCONPW="potentate"
  #     - SRCDS_PW="potentate"
  #     - SRCDS_PORT=27017
  #     - SRCDS_TV_PORT=27020
  #     - SRCDS_NET_PUBLIC_ADDRESS="0"
  #     - SRCDS_IP=""
  #     - SRCDS_FPSMAX=300
  #     - SRCDS_TICKRATE=128
  #     - SRCDS_MAXPLAYERS=20
  #     - SRCDS_STARTMAP="cs_office"
  #     - SRCDS_REGION=3
  #     - SRCDS_MAPGROUP="mg_active"
  #     - SRCDS_GAMETYPE=0
  #     - SRCDS_GAMEMODE=1
  #     - SRCDS_HOSTNAME="NoxLAN - Counterstrike Global Offensive"
  #     - SRCDS_WORKSHOP_START_MAP=0
  #     - SRCDS_HOST_WORKSHOP_COLLECTION=0
  #     - ADDITIONAL_ARGS=""
  #   networks:
  #     enp1s0f1_vlan:
  #       ipv4_address: "192.168.100.40"
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped
  #   volumes:
  #     - /mnt/store/docker-volumes/csgo/:/home/steam/csgo-dedicated/

  # csgo-gg:
  #   image: csgo-gg:latest
  #   container_name: gameserver-csgo-gg
  #   environment:
  #     - MAP="de_dust"
  #     - MAX_PLAYERS=24
  #     - SV_HOSTNAME="NoxLAN - Counterstrike Global Offensive - Gun Game"
  #     - LAN=1
  #   networks:
  #     enp1s0f1_vlan:
  #       ipv4_address: "192.168.100.41"
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped

  # tf2:
  #   image: ghcr.io/melkortf/tf2-sourcemod:latest
  #   container_name: gameserver-tf2
  #   env_file:
  #     - rcon.env
  #   environment:
  #     - MAP="cp_manor_event"
  #     - SERVER_HOSTNAME=NoxLAN - Team Fortress 2
  #     - LAN=1
  #   networks:
  #     enp1s0f1_vlan:
  #       ipv4_address: "192.168.100.50"
  #   restart: unless-stopped

  # tf2-mvm:
  #   image: tf2-melkort-mvm:latest
  #   container_name: gameserver-tf2-mvm
  #   env_file:
  #     - rcon.env
  #   environment:
  #     - MAP="mvm_coaltown"
  #     - SERVER_HOSTNAME=NoxLAN - MVM Team Fortress 2
  #     - LAN=1
  #   networks:
  #     enp1s0f1_vlan:
  #       ipv4_address: "192.168.100.51"
  #   restart: unless-stopped

  scpsl:
    image: scpsl-exiled:latest
    container_name: gameserver-scpsl
    environment:
      - SERVER_PORT=7777
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.60"
    stdin_open: true
    tty: true
    restart: unless-stopped

  insurgency-pvp:
    image: insurgency:latest
    container_name: gameserver-insurgency-survival
    env_file:
      - rcon.env
    environment:
      - SV_HOSTNAME="NoxLAN - Insurgency - Survival"
      - MAPCYCLEFILE=mapcycle_survival.txt
      - SERVER_CFG=default_server_survival.cfg
      - GAME_MODE=conquest
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.70"
    stdin_open: true
    tty: true
    restart: unless-stopped

  insurgency-coop:
    image: insurgency:latest
    container_name: gameserver-insurgency-coop
    env_file:
      - rcon.env
    environment:
      - SV_HOSTNAME="NoxLAN - Insurgency - Coop"
      - MAPCYCLEFILE="mapcycle_cooperative.txt"
      - SERVER_CFG="default_server_survival.cfg"
      - GAME_MODE=survival
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.71"
    stdin_open: true
    tty: true
    restart: unless-stopped

  ut99:
    !!merge <<: *ut99-base
    container_name: gameserver-ut99
    environment:
      - UT_SERVERURL="CTF-Face?game=BotPack.CTFGame?mutator=MVES.MapVote,FlagAnnouncementsV2.FlagAnnouncements"
      - UT_SERVERNAME="NoxLAN UT99 Server"
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.74"
    stdin_open: true
    tty: true
    restart: unless-stopped

  ut99-instagib:
    !!merge <<: *ut99-base
    container_name: gameserver-ut99-instagib
    environment:
      - UT_SERVERURL="CTF-Face?game=BotPack.CTFGame?mutator=BotPack.InstaGibDM,MVES.MapVote,FlagAnnouncementsV2.FlagAnnouncements"
      - UT_SERVERNAME="NoxLAN UT99 Server - Instagib"
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.75"
    stdin_open: true
    tty: true
    restart: unless-stopped

  ut2004:
    !!merge <<: *ut2004-base
    container_name: gameserver-ut2004
    environment:
      - SV_HOSTNAME="NoxLAN UT2004 Server"
      - MAP=CTF-Face3
      - MAPVOTE_TYPE="DM,CTF,AS,DOM,ONS"
      - INSTAGIB="0"             # Set to 1 for InstaGib
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.76"
    stdin_open: true
    tty: true
    restart: unless-stopped

  ut2004-instagib:
    !!merge <<: *ut2004-base
    container_name: gameserver-ut2004-instagib
    environment:
      - SV_HOSTNAME="NoxLAN UT2004 Server - Instagib"
      - MAP=CTF-Face3
      - MAPVOTE_TYPE="DM,CTF,AS,DOM,ONS"
      - INSTAGIB="1"             # Set to 1 for InstaGib
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.77"
    stdin_open: true
    tty: true
    restart: unless-stopped

  openttd:
    image: openttd:latest
    container_name: gameserver-openttd
    environment:
      - SERVER_NAME="NoxLAN - OpenTTD"
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.80"
    restart: unless-stopped

  trackmania-forever:
    image: trackmania-forever:latest
    container_name: gameserver-trackmania
    environment:
      - SERVER_NAME=NoxLAN - TrackMania Nations
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.82"
    restart: unless-stopped

  intranet:
    image: nginx:latest
    volumes:
      - ./intranet:/usr/share/nginx/html:ro
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      enp1s0f1_vlan:
        ipv4_address: "192.168.100.5"
    restart: unless-stopped

  ftp:
    image: noxtech/anonymous-pure-ftp
    container_name: gameserver-ftp
    environment:
      - FTP_PASSIVE_PORTS=40000 40039
    ports:
      - "21:21"
      - "40000-40039:40000-40039"
    volumes:
      - "/srv/store/docker-volumes/ftp/data:/data"
      - "/srv/store/docker-volumes/ftp/etc/pure-ftpd/:/etc/pure-ftpd/"
    restart: unless-stopped

  ptokax:
    image: ruben69695/ptokax:latest
    container_name: gameserver-ptokax
    ports:
      - "192.168.100.2:1412:1412"
      - "192.168.100.2:411:411/tcp"
      - "192.168.100.2:412:412"
      - "192.168.100.2:413:413/udp"
      - "192.168.100.2:9000-9999:9000-9999"
    volumes:
      - /srv/store/docker-volumes/ptokax/config:/src/cfg-custom
      - /srv/store/docker-volumes/ptokax/logs:/src/logs
    entrypoint: /bin/sh -c "mkdir -p /src/cfg/ && cp -r /src/cfg-custom/* /src/cfg/ && exec ./PtokaX"
    restart: unless-stopped

#  airdcpp:
#    image: gangefors/airdcpp-webclient
#    container_name: gameserver-air-dcpp
#    volumes:
#      - airdcpp:/.airdcpp
#      - "${DL_DIR:-$HOME/Downloads}:/Downloads"
#      - "${SHARE_DIR:-$HOME/Share}:/Share"
#    environment:
#      - PUID=${PUID:-1000}
#      - PGID=${PGID:-1000}
#      - UMASK=${UMASK:-0022}
#    hostname: airdcpp
#    ports:
#      - ${HTTP_PORT:-80}:5600
#      - ${HTTPS_PORT:-443}:5601
#      - ${TCP_PORT:-21248}:${TCP_PORT:-21248}
#      - ${UDP_PORT:-21248}:${UDP_PORT:-21248}/udp
#      - ${TLS_PORT:-21249}:${TLS_PORT:-21249}

networks:
  enp1s0f1_vlan:
    name: enp1s0f1_vlan
    driver: macvlan
    driver_opts:
      parent: enp1s0f1
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  airdcpp:
    driver: local
