version: '2'

services:

  l4d2-campaign:
    image: l4d2-metamod:latest
    container_name: gameserver-l4d2-campaign
    environment:
      - MAP="c2m1_highway"
      - MP_GAMEMODE="coop"
      - MAX_PLAYERS=4
      - SV_HOSTNAME="NoxLAN - Left 4 Dead 2 - Campaign"
      - LAN=1
      - RCON_PASSWORD="changeme"
      - FULL_ADMINS="STEAM_1:0:7970889" "99:z"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.150"
    stdin_open: true
    tty: true
    restart: unless-stopped

  l4d2-versus:
    image: l4d2-metamod:latest
    container_name: gameserver-l4d2-versus
    environment:
      - MAP="c2m1_highway"
      - MP_GAMEMODE="versus"
      - MAX_PLAYERS=8
      - SV_HOSTNAME="NoxLAN - Left 4 Dead 2 - Versus"
      - LAN=1
      - RCON_PASSWORD="changeme"
      - FULL_ADMINS="STEAM_1:0:7970889" "99:z"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.151"
    stdin_open: true
    tty: true
    restart: unless-stopped

  l4d2-versus-abm:
    image: l4d2-abm:latest
    container_name: gameserver-l4d2-versus-abm
    environment:
      - MAP="c2m1_highway"
      - MP_GAMEMODE="versus"
      - MAX_PLAYERS=16
      - SV_HOSTNAME="NoxLAN - Left 4 Dead 2 - Versus (8v8)"
      - LAN=1
      - RCON_PASSWORD="changeme"
      - FULL_ADMINS="STEAM_1:0:7970889" "99:z"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.152"
    stdin_open: true
    tty: true
    restart: unless-stopped

  l4d2-campaign-abm:
    image: l4d2-abm:latest
    container_name: gameserver-l4d2-campaign-abm
    environment:
      - MAP="c2m1_highway"
      - MP_GAMEMODE="coop"
      - MAX_PLAYERS=8
      - SV_HOSTNAME="NoxLAN - Left 4 Dead 2 - Campaign (8 players)"
      - LAN=1
      - RCON_PASSWORD="changeme"
      - FULL_ADMINS="STEAM_1:0:7970889" "99:z"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.153"
    stdin_open: true
    tty: true
    restart: unless-stopped

  css:
    image: css-metamod:latest
    container_name: gameserver-css
    environment:
      - BOT_QUOTA=12
      - MP_FRIENDLYFIRE=1
      - MP_MAXROUNDS=7
      - MP_AUTOTEAMBALANCE=1
      - MAP="de_dust"
      - MAX_PLAYERS=24
      - SV_HOSTNAME="NoxLAN - Counterstrike Source"
      - LAN=1
      - RCON_PASSWORD="changeme"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.154"
    stdin_open: true
    tty: true
    restart: unless-stopped

  css-hideandseek:
    image: css-hideandseek:latest
    container_name: gameserver-css-hideandseek
    environment:
      - MAP="cs_office"
      - MAX_PLAYERS=24
      - SV_HOSTNAME="NoxLAN - Counterstrike Source - (Hide and Seek)"
      - LAN=1
      - RCON_PASSWORD="changeme"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.155"
    stdin_open: true
    tty: true
    restart: unless-stopped

  css-gungame:
    image: css-gungame:latest
    container_name: gameserver-css-gungame
    environment:
      - MAP="de_dust2"
      - MAX_PLAYERS=24
      - SV_HOSTNAME="NoxLAN - Counterstrike Source - (GunGame)"
      - LAN=1
      - RCON_PASSWORD="changeme"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.156"
    stdin_open: true
    tty: true
    restart: unless-stopped

  csgo:
    image: csgo-metamod:latest
    container_name: gameserver-csgo
    environment:
      - MAP="cs_office"
      - MAX_PLAYERS=24
      - SV_HOSTNAME="NoxLAN - Counterstrike Global Offensive"
      - LAN=1
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.154"
    stdin_open: true
    tty: true
    restart: unless-stopped

  # csgo-gg:
  #   image: csgo-gg:latest
  #   container_name: gameserver-csgo-gg
  #   environment:
  #     - MAP="de_dust"
  #     - MAX_PLAYERS=24
  #     - SV_HOSTNAME="NoxLAN - Counterstrike Global Offensive - Gun Game"
  #     - LAN=1
  #   networks:
  #     enp1s0f0_vlan:
  #       ipv4_address: "192.168.0.155"
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped

  insurgency-pvp:
    image: insurgency:latest
    container_name: gameserver-insurgency-pvp
    environment:
      - SV_HOSTNAME="NoxLAN - Insurgency - Conquest"
      - MAPCYCLEFILE=mapcycle_tactical_operations.txt
      - SERVER_CFG=default_server_battle.cfg
#      - GAME_MODE=conquest
      - RCON_PASSWORD="changeme"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.157"
    restart: unless-stopped

  insurgency-coop:
    image: insurgency:latest
    container_name: gameserver-insurgency-coop
    environment:
      - SV_HOSTNAME="NoxLAN - Insurgency - Coop"
#      - MAPCYCLEFILE="mapcycle_tactical_operations.txt"
#      - SERVER_CFG="default_server_survival.cfg"
      - GAME_MODE=survival
      - RCON_PASSWORD="changeme"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.158"
    restart: unless-stopped

  tf2:
    image: tf2:latest
    container_name: gameserver-tf2
    environment:
      - MAP="cp_manor_event"
      - SV_HOSTNAME="NoxLAN - Team Fortress 2"
      - LAN=1
      - RCON_PASSWORD="changeme"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.159"
    restart: unless-stopped

  openttd:
    image: openttd:latest
    container_name: gameserver-openttd
    environment:
      - SERVER_NAME="NoxLAN - OpenTTD"
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.160"
    restart: unless-stopped

  trackmania-forever:
    image: trackmania-forever:latest
    container_name: gameserver-trackmania
    environment:
      - SERVER_NAME=NoxLAN - TrackMania Nations
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.161"
    restart: unless-stopped

  scpsl:
    image: scpsl:latest
    container_name: gameserver-scpsl
    environment:
      - SERVER_PORT=7777
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.162"
    restart: unless-stopped

  bf3vu:
    image: bf3vu:latest
    container_name: gameserver-bf3vu
    env_file:
      - bf3vu.env
    environment:
      - JOINHOST=192.168.0.163
    networks:
      enp1s0f0_vlan:
        ipv4_address: "192.168.0.163"
    restart: unless-stopped
    volumes:
      - /mnt/store/docker-volumes/vu/bf3:/vu/bf3
      - /mnt/store/docker-volumes/vu/instance:/vu/instance
      - bf3vu-client-volume:/vu/client

networks:
  enp1s0f0_vlan:
    external:
      name: enp1s0f0_vlan

volumes:
  bf3vu-client-volume:
